[platformio]
extra_configs =
    secrets.ini

[env:seeed_xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
upload_protocol = esptool
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit MQTT Library
    claws/BH1750
lib_ignore =
    WiFiNINA
    WiFiNINA_-_Adafruit_Fork
    WiFi101
    Adafruit_WiFiNINA